ejercicio02/ejercicio02/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('usuarios.urls'))
]

ejercicio02/usuarios/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .views import Registro

app_name = "usuarios"

urlpatterns = [
    path('', views.Principal.as_view(), name = 'principal'),
    path('login/', auth_views.LoginView.as_view(template_name = 'usuarios/login.html'), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'usuarios/login.html'), name = 'logout'),
    path('registro/', Registro.as_view(), name='registro')

]

ejercicio02/usuarios/models.py
from django.db import models

# Create your models here.

ejercicio02/usuarios/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy


# Create your views here.

class Principal(LoginRequiredMixin, generic.TemplateView):
    template_name = 'usuarios/principal.html'
    login_url='usuarios:login'

class Registro(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('usuarios:principal')
    template_name = 'usuarios/registro.html'

ejercicio02/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/cssgrid.css' %}">
    <title>Main</title>
</head>
    <body>
        <div id="cg" class="grid-container2">
            <div id="block1" class="c_rojo">1</div>
            <div id="block2" class="c_verde">2</div>
            <div id="block3" class="c_azul">{% block logout %}3{% endblock logout %}</div>
            <div id="block4" class="c_rojo">4</div>
            <div id="block7" class="c_verde">7</div>
            <div id="block5" class="grid-container5">
                <div id="block5a" class="grid-container5a">
                    {% block principal1 %}
                    <div id="block5a1">
                        <center><div class="bcontainer">
                            <button id="boton1" style="background-color: white;" class="boton">Boton 1</button>
                        </div></center>
                    </div>
                    <div id="block5a2">
                        <center><div class="bcontainer">
                            <button id="boton2" style="background-color: white;" class="boton">Boton 2</button>
                        </div></center>
                    </div>
                    <div id="block5a3">
                        <center><div class="bcontainer">
                            <button id="boton3" style="background-color: white;" class="boton">Boton 3</button>
                        </div></center>
                    </div>
                    {% endblock principal1 %}
                </div>
                <div id="block5b" class="grid-container5b">
                    {% block principal2 %}
                    <center><div id="block5b1" class="circulo" style="background: red;">
                        
                            <p>Todo Rojo</p>
                        
                    </div></center>
                    <center><div id="block5b2" class="circulo" style="background:green;">
                        
                            <p>Todo Verde</p>
                        
                    </div></center>
                    <center><div id="block5b3" class="circulo" style="background: blue;">
                        
                            <p>Todo Azul</p>
                        
                    </div></center>
                    {% endblock principal2 %}
                </div>
            </div>
            <div id="block6" class="c_rojo">6</div>
            <div id="block9" class="c_azul">9</div>
            <div id="block10" class="c_azul">10</div>
            <div id="block11" class="c_verde">11</div>
            <div id="block12" class="c_rojo">12</div>
        </div>
    </body>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
integrity="sha256-4+XzXVhsDmqanXGHaHvgh1gMQKX40OUvDEBTu8JcmNs="
crossorigin="anonymous"></script>
    <script src="{% static 'js/jsgrid.js' %}"></script>
</html>

ejercicio02/templates/base1.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/cssgrid.css' %}">
    <title>Main</title>
</head>
    <body>
        <div id="cg" class="grid-container2">
            <div id="block1" class="c_rojo">1</div>
            <div id="block2" class="c_verde">2</div>
            <div id="block3" class="c_azul">3</div>
            <div id="block4" class="c_rojo">4</div>
            <div id="block7" class="c_verde">7</div>
            <div id="block5">
                <div id="contenedor_superior" class="contenedor">
                    {% block principal1 %}
                    <div id="block8-1">
                        <center><div class="bcontainer">
                            <button id="boton1" class="boton">Boton 1</button>
                        </div></center>
                    </div>
                    <div id="block8-2">
                        <center><div class="bcontainer">
                            <button id="boton2" class="boton">Boton 2</button>
                        </div></center>
                    </div>
                    <div id="block8-3">
                        <center><div class="bcontainer">
                            <button id="boton3" class="boton">Boton 3</button>
                        </div></center>
                    </div>
                    {% endblock principal1 %}
                </div>
            </div>
            <div id="block8">
                <div id="contenedor_inferior" class="contenedor">
                    {% block principal2 %}
                    <center><div id="block8-1" class="circulo" style="background: red;">
                        
                            <p>Todo Rojo</p>
                        
                    </div></center>
                    <center><div id="block8-2" class="circulo" style="background:green;">
                        
                            <p>Todo Verde</p>
                        
                    </div></center>
                    <center><div id="block8-3" class="circulo" style="background: blue;">
                        
                            <p>Todo Azul</p>
                        
                    </div></center>
                    {% endblock principal2 %}
                </div>
            </div>
            <div id="block6" class="c_rojo">6</div>
            <div id="block9" class="c_azul">9</div>
            <div id="block10" class="c_azul">10</div>
            <div id="block11" class="c_verde">11</div>
            <div id="block12" class="c_rojo">12</div>
        </div>
    </body>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
integrity="sha256-4+XzXVhsDmqanXGHaHvgh1gMQKX40OUvDEBTu8JcmNs="
crossorigin="anonymous"></script>
    <script src="{% static 'js/jsgrid.js' %}"></script>
</html>

ejercicio02/usuarios/templates/usuarios/login.html
{% extends 'base.html' %}

{% block principal1 %}

<div id="warning">
<table>
{% if form.errors %}
    {% for campos in form%}
        {% if campos.errors %}
            {% for error in campos.errors%}
            <tr>
                 <td>{{ error|escape }}</td>
            </tr>
            {%endfor%}
        {% endif %}
    {% endfor %}

    {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
        <tr>
            <td>{{ error|escape }}</td>
       </tr>
        {% endfor %}
    {% endif %}

{% endif %}
</table>
</div>
    <form action="" method="POST">
        {% csrf_token %}
        <table>
            <tr>
                <td><input type="text" id="id_username" name="username" placeholder="Usuario"></td>
            </tr>
            <tr>
                <td><input type="password" id="id_password" name="password" placeholder="Password"></td>
            </tr>
            <tr>
                <td><button type="submit">Acceder</button></td>
            </tr>
        </table>    
    </form>
{%endblock principal1%}

{% block principal2 %}
<a href="{% url 'usuarios:registro' %}"><button type="button">Registrar</button></a>
{%endblock principal2%}

ejercicio02/usuarios/templates/usuarios/principal.html
{% extends 'base.html' %}
{% block logout %}
<a href="{% url 'usuarios:logout' %}"><button type="button">Salir</button></a>
{% endblock logout %}

ejercicio02/usuarios/templates/usuarios/registro.html
{% extends 'base.html'%}

{% block principal1 %}
<div>
<h2>Registro de Usuario</h2>
<form method="post" id="registro">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Aceptar</button>
</form>
</div>
{% endblock principal1 %}

{% block principal2%}
{% endblock principal2%}